version: '1.0.{build}'
image: 
  - Ubuntu
services:
  - docker
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
build_script:
  - docker pull mcr.microsoft.com/mssql/server:2017-latest || true
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=<YourStrong!Passw0rd>' -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server:2017-latest || true
  - docker exec -i sql1 /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '<YourStrong!Passw0rd>' -Q 'ALTER LOGIN SA WITH PASSWORD="<YourNewStrong!Passw0rd>"' || true
  - dotnet ef database update --project source/TodoList.Infrastructure --startup-project source/TodoList.WebApi
  - dotnet build
  - cd source/TodoList.ConsoleApp/
  - dotnet pack --configuration Release
test_script:
  - dotnet test tests/TodoList.UnitTests/TodoList.UnitTests.csproj
  - dotnet test tests/TodoList.IntegrationTests/TodoList.IntegrationTests.csproj
  - dotnet test tests/TodoList.AcceptanceTests/TodoList.AcceptanceTests.csproj
deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: w3VEkxHD76f281nKX7yKFKfzka1YdBlb3wXL/yqZ65mC5iJZSSJw5hsUXOboHpCx
    skip_symbols: true
    artifact: /.*\.nupkg/